data_folder = "/Users/AnhVu/Study/PhD/mypaper/online_deep_forest/data/csv"

file_list = [
    "electricity-normalized"
    # "GMSC",
    # "covtype-normalized",
    # "airlines",
    # "mnist_5_5_abrupt",
    # "nomao",
    # "KDDCup99_full",
]

file_list2 = [
    "BayesianNetworkGenerator_tic-tac-toe",
    "electricity-normalized",
    "dataset_183_adult",
    "BNG_cmc",
    "BayesianNetworkGenerator_vote",
    "vehicleNorm",
    "Stagger3",
    "Stagger2",
    "Stagger1",
    "SEA_50000",
    "SEA_50",
    "RandomRBF_50_1E-4",
    "RandomRBF_50_1E-3",
]

file_list1 = [
    "20_newsgroups.drift",
    "Agrawal1",
    "airlines",
    "AirlinesCodrnaAdult",
    "AssetNegotiation-F2",
    "AssetNegotiation-F3",
    "AssetNegotiation-F4",
    "BayesianNetworkGenerator_kr-vs-kp_small",
    "BayesianNetworkGenerator_mushroom",
    "BayesianNetworkGenerator_soybean",
    "BayesianNetworkGenerator_tic-tac-toe",
    "BayesianNetworkGenerator_trains",
    "BayesianNetworkGenerator_vote",
    "BNG_bridges_version1",
    "BNG_cmc",
    "BNG_credit-a",
    "BNG_dermatology",
    "BNG_heart-c",
    "BNG_heart-statlog",
    "BNG_hepatitis",
    "BNG_JapaneseVowels",
    "BNG_labor",
    "BNG_letter",
    "BNG_lymph",
    "BNG_mfeat-fourier",
    "BNG_page-blocks",
    "BNG_pendigits",
    "BNG_satimage",
    "BNG_solar-flare",
    "BNG_sonar",
    "BNG_SPECT",
    "BNG_vehicle",
    "BNG_vowel",
    "BNG_waveform-5000",
    "BNG_wine",
    "BNG_zoo",
    "BNG(anneal)",
    "BNG(credit-g)",
    "BNG(ionosphere)",
    "BNG(optdigits)",
    "BNG(segment)",
    "BNG(spambase)",
    "codrnaNorm",
    "CovPokElec",
    "covtype-normalized",
    "dataset_183_adult",
    "electricity-normalized",
    "Hyperplane_10_1E-3",
    "Hyperplane_10_1E-4",
    "IMDB-F.drama",
    "KDDCup99_full",
    "LED_50000",
    "pokerhand-normalized",
    "RandomRBF_0_0",
    "RandomRBF_10_1E-3",
    "RandomRBF_10_1E-4",
    "RandomRBF_50_1E-3",
    "RandomRBF_50_1E-4",
    "SEA_50",
    "SEA_50000",
    "Stagger1",
    "Stagger2",
    "Stagger3",
    "vehicleNorm"
]
